pipeline{
	agent any
	stages{
		stage("job1"){
				steps{
					echo "job1"
				}
			}
		stage("job2"){
				steps{
					echo "job2"
				}
			}
		stage("any"){
			steps{
				echo "hi"
				}
			}
		}
	}	
